/*
 * Generate stackpeek/data/logos.js — a map of technology name -> { hex, path }
 * using Simple Icons (CC0). Inlined so the extension needs no extra files and
 * makes zero network requests. Unmatched technologies fall back to a monogram
 * tile in the UI.
 */
const fs = require('fs');
const path = require('path');
const si = require('simple-icons');

// slug -> icon object index
const bySlug = {};
for (const k of Object.keys(si)) {
  const ic = si[k];
  if (ic && ic.slug) { bySlug[ic.slug] = ic; }
}

// StackPeek fingerprint name -> Simple Icons slug (best match; null = fallback)
const MAP = {
  'WordPress': 'wordpress', 'Shopify': 'shopify', 'Wix': 'wix', 'Squarespace': 'squarespace',
  'Webflow': 'webflow', 'Joomla': 'joomla', 'Drupal': 'drupal', 'Ghost': 'ghost',
  'BigCommerce': 'bigcommerce', 'Magento / Adobe Commerce': 'magento', 'HubSpot CMS': 'hubspot',
  'Contentful': 'contentful', 'Sanity': 'sanity', 'Craft CMS': 'craftcms', 'TYPO3': 'typo3',
  'WooCommerce': 'woocommerce', 'Klaviyo': 'klaviyo', 'Yotpo': 'yotpo',
  'React': 'react', 'Vue.js': 'vuedotjs', 'Next.js': 'nextdotjs', 'Nuxt.js': 'nuxt',
  'Angular': 'angular', 'Svelte / SvelteKit': 'svelte', 'jQuery': 'jquery', 'Gatsby': 'gatsby',
  'Alpine.js': 'alpinedotjs', 'Ember.js': 'emberdotjs', 'Preact': 'preact', 'Backbone.js': 'backbonedotjs',
  'Remix': 'remix', 'Astro': 'astro', 'SolidJS': 'solid',
  'Bootstrap': 'bootstrap', 'Tailwind CSS': 'tailwindcss', 'Material UI': 'mui',
  'styled-components': 'styledcomponents', 'Ant Design': 'antdesign', 'Chakra UI': 'chakraui', 'Bulma': 'bulma',
  'Lodash': 'lodash', 'Axios': 'axios', 'GSAP': 'greensock', 'Swiper': 'swiper', 'D3.js': 'd3',
  'Elementor': 'elementor',
  'Google Analytics 4': 'googleanalytics', 'Google Analytics (Universal)': 'googleanalytics',
  'Hotjar': 'hotjar', 'Mixpanel': 'mixpanel', 'Amplitude': 'amplitude', 'Plausible': 'plausibleanalytics',
  'Matomo': 'matomo',
  'Optimizely': 'optimizely',
  'Google Tag Manager': 'googletagmanager',
  'Google AdSense': 'googleadsense', 'Facebook Pixel': 'facebook', 'X (Twitter) Pixel': 'x',
  'LinkedIn Insight Tag': 'linkedin', 'TikTok Pixel': 'tiktok', 'Pinterest Tag': 'pinterest',
  'Snapchat Pixel': 'snapchat',
  'Sentry': 'sentry', 'New Relic': 'newrelic', 'Datadog RUM': 'datadog',
  'Intercom': 'intercom', 'Zendesk': 'zendesk', 'Crisp': 'crisp', 'LiveChat': 'livechat',
  'Stripe': 'stripe', 'PayPal': 'paypal', 'Razorpay': 'razorpay', 'Square': 'square', 'Adyen': 'adyen',
  'YouTube': 'youtube', 'Vimeo': 'vimeo', 'Wistia': 'wistia',
  'Google Maps': 'googlemaps', 'Mapbox': 'mapbox', 'Leaflet': 'leaflet',
  'Google Fonts': 'googlefonts', 'Font Awesome': 'fontawesome',
  'Cloudflare Turnstile': 'cloudflare',
  'Akamai': 'akamai',
  'Cloudflare': 'cloudflare', 'Vercel': 'vercel', 'Netlify': 'netlify', 'AWS CloudFront': 'amazonwebservices',
  'Fastly': 'fastly', 'jsDelivr': 'jsdelivr', 'cdnjs (Cloudflare)': 'cloudflare',
  'GitHub Pages': 'github',
  'Nginx': 'nginx', 'Apache': 'apache',
  'PHP': 'php', 'ASP.NET': 'dotnet', 'Ruby on Rails': 'rubyonrails', 'Express': 'express',
  'RSS / Atom Feed': 'rss', 'OneSignal': 'onesignal', 'Mailchimp': 'mailchimp'
};

const out = {};
const missing = [];
for (const [name, slug] of Object.entries(MAP)) {
  if (slug && bySlug[slug]) {
    out[name] = { h: bySlug[slug].hex, p: bySlug[slug].path };
  } else {
    missing.push(name + (slug ? ' (slug "' + slug + '" not found)' : ' (no slug)'));
  }
}

const header = '/*\n' +
  ' * StackPeek — technology logos (auto-generated by scripts/gen_logos.js).\n' +
  ' * Brand marks from Simple Icons (https://simpleicons.org), CC0 1.0.\n' +
  ' * Map: technology name -> { h: brand hex, p: single SVG path (viewBox 0 0 24 24) }.\n' +
  ' * Technologies without an entry render a lettered monogram in the UI.\n' +
  ' */\n';
const body = '(function(){\n  var LOGOS = ' + JSON.stringify(out) + ';\n' +
  '  if (typeof module !== "undefined" && module.exports) { module.exports = LOGOS; }\n' +
  '  if (typeof window !== "undefined") { window.SP_LOGOS = LOGOS; }\n})();\n';

fs.writeFileSync(path.join(__dirname, '..', 'stackpeek', 'data', 'logos.js'), header + body);
console.log('logos written:', Object.keys(out).length, 'matched /', Object.keys(MAP).length, 'mapped');
console.log('missing (' + missing.length + '):', missing.join(', '));
